// Code generated by goctl. DO NOT EDIT.
// versions:
//  goctl version: 1.9.2

package model

import (
	"context"
	"database/sql"
	"fmt"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/cache"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	shortUrlMapFieldNames          = builder.RawFieldNames(&ShortUrlMap{})
	shortUrlMapRows                = strings.Join(shortUrlMapFieldNames, ",")
	shortUrlMapRowsExpectAutoSet   = strings.Join(stringx.Remove(shortUrlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	shortUrlMapRowsWithPlaceHolder = strings.Join(stringx.Remove(shortUrlMapFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"

	cacheGoShortenerShortUrlMapIdPrefix   = "cache:goShortener:shortUrlMap:id:"
	cacheGoShortenerShortUrlMapMd5Prefix  = "cache:goShortener:shortUrlMap:md5:"
	cacheGoShortenerShortUrlMapSurlPrefix = "cache:goShortener:shortUrlMap:surl:"
)

type (
	shortUrlMapModel interface {
		Insert(ctx context.Context, data *ShortUrlMap) (sql.Result, error)
		FindOne(ctx context.Context, id uint64) (*ShortUrlMap, error)
		FindOneByMd5(ctx context.Context, md5 sql.NullString) (*ShortUrlMap, error)
		FindOneBySurl(ctx context.Context, surl sql.NullString) (*ShortUrlMap, error)
		Update(ctx context.Context, data *ShortUrlMap) error
		Delete(ctx context.Context, id uint64) error
	}

	defaultShortUrlMapModel struct {
		sqlc.CachedConn
		table string
	}

	ShortUrlMap struct {
		Id       uint64         `db:"id"`        // 主键
		CreateAt time.Time      `db:"create_at"` // 创建时间
		CreateBy string         `db:"create_by"` // 创建者
		IsDel    uint64         `db:"is_del"`    // 是否删除：0正常1删除
		Lurl     sql.NullString `db:"lurl"`      // ⻓链接
		Md5      sql.NullString `db:"md5"`       // ⻓链接MD5
		Surl     sql.NullString `db:"surl"`      // 短链接
		ExpireAt sql.NullTime   `db:"expire_at"` // 过期时间
	}
)

func newShortUrlMapModel(conn sqlx.SqlConn, c cache.CacheConf, opts ...cache.Option) *defaultShortUrlMapModel {
	return &defaultShortUrlMapModel{
		CachedConn: sqlc.NewConn(conn, c, opts...),
		table:      "`short_url_map`",
	}
}

func (m *defaultShortUrlMapModel) Delete(ctx context.Context, id uint64) error {
	data, err := m.FindOne(ctx, id)
	if err != nil {
		return err
	}

	goShortenerShortUrlMapIdKey := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapIdPrefix, id)
	goShortenerShortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapMd5Prefix, data.Md5)
	goShortenerShortUrlMapSurlKey := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapSurlPrefix, data.Surl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
		return conn.ExecCtx(ctx, query, id)
	}, goShortenerShortUrlMapIdKey, goShortenerShortUrlMapMd5Key, goShortenerShortUrlMapSurlKey)
	return err
}

func (m *defaultShortUrlMapModel) FindOne(ctx context.Context, id uint64) (*ShortUrlMap, error) {
	goShortenerShortUrlMapIdKey := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapIdPrefix, id)
	var resp ShortUrlMap
	err := m.QueryRowCtx(ctx, &resp, goShortenerShortUrlMapIdKey, func(ctx context.Context, conn sqlx.SqlConn, v any) error {
		query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shortUrlMapRows, m.table)
		return conn.QueryRowCtx(ctx, v, query, id)
	})
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) FindOneByMd5(ctx context.Context, md5 sql.NullString) (*ShortUrlMap, error) {
	goShortenerShortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapMd5Prefix, md5)
	var resp ShortUrlMap
	err := m.QueryRowIndexCtx(ctx, &resp, goShortenerShortUrlMapMd5Key, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `md5` = ? limit 1", shortUrlMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, md5); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) FindOneBySurl(ctx context.Context, surl sql.NullString) (*ShortUrlMap, error) {
	goShortenerShortUrlMapSurlKey := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapSurlPrefix, surl)
	var resp ShortUrlMap
	err := m.QueryRowIndexCtx(ctx, &resp, goShortenerShortUrlMapSurlKey, m.formatPrimary, func(ctx context.Context, conn sqlx.SqlConn, v any) (i any, e error) {
		query := fmt.Sprintf("select %s from %s where `surl` = ? limit 1", shortUrlMapRows, m.table)
		if err := conn.QueryRowCtx(ctx, &resp, query, surl); err != nil {
			return nil, err
		}
		return resp.Id, nil
	}, m.queryPrimary)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultShortUrlMapModel) Insert(ctx context.Context, data *ShortUrlMap) (sql.Result, error) {
	goShortenerShortUrlMapIdKey := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapIdPrefix, data.Id)
	goShortenerShortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapMd5Prefix, data.Md5)
	goShortenerShortUrlMapSurlKey := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapSurlPrefix, data.Surl)
	ret, err := m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?)", m.table, shortUrlMapRowsExpectAutoSet)
		return conn.ExecCtx(ctx, query, data.CreateBy, data.IsDel, data.Lurl, data.Md5, data.Surl, data.ExpireAt)
	}, goShortenerShortUrlMapIdKey, goShortenerShortUrlMapMd5Key, goShortenerShortUrlMapSurlKey)
	return ret, err
}

func (m *defaultShortUrlMapModel) Update(ctx context.Context, newData *ShortUrlMap) error {
	data, err := m.FindOne(ctx, newData.Id)
	if err != nil {
		return err
	}

	goShortenerShortUrlMapIdKey := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapIdPrefix, data.Id)
	goShortenerShortUrlMapMd5Key := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapMd5Prefix, data.Md5)
	goShortenerShortUrlMapSurlKey := fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapSurlPrefix, data.Surl)
	_, err = m.ExecCtx(ctx, func(ctx context.Context, conn sqlx.SqlConn) (result sql.Result, err error) {
		query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, shortUrlMapRowsWithPlaceHolder)
		return conn.ExecCtx(ctx, query, newData.CreateBy, newData.IsDel, newData.Lurl, newData.Md5, newData.Surl, newData.ExpireAt, newData.Id)
	}, goShortenerShortUrlMapIdKey, goShortenerShortUrlMapMd5Key, goShortenerShortUrlMapSurlKey)
	return err
}

func (m *defaultShortUrlMapModel) formatPrimary(primary any) string {
	return fmt.Sprintf("%s%v", cacheGoShortenerShortUrlMapIdPrefix, primary)
}

func (m *defaultShortUrlMapModel) queryPrimary(ctx context.Context, conn sqlx.SqlConn, v, primary any) error {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", shortUrlMapRows, m.table)
	return conn.QueryRowCtx(ctx, v, query, primary)
}

func (m *defaultShortUrlMapModel) tableName() string {
	return m.table
}
